default_platform(:android)

platform :android do
  desc "Lane for distributing app using Github releases"
  lane :github do
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "/home/runner/work/YouAMP/YouAMP/keystore.jks",
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEYSTORE_KEY_PASSWORD'],
      }
    )
    set_github_release(
      repository_name: "siper/YouAMP",
      api_token: ENV['TOKEN_GITHUB'],
      name: ENV['VERSION_TAG'],
      tag_name: ENV['VERSION_TAG'],
      upload_assets: ["app/build/outputs/apk/release/app-release.apk"]
    )
    track = 'release'
    if ENV['VERSION_TAG'].include? 'alpha'
      track = 'internal'
    elsif ENV['VERSION_TAG'].include? 'beta'
      track = 'beta'
    else
      track = 'release'
    end
    upload_to_play_store(track: 'beta')
  end
  lane :play_store do
    gradle(
          task: "assemble",
          build_type: "Release",
          properties: {
            "android.injected.signing.store.file" => "/home/runner/work/YouAMP/YouAMP/keystore.jks",
            "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
            "android.injected.signing.key.alias" => ENV['KEYSTORE_KEY_ALIAS'],
            "android.injected.signing.key.password" => ENV['KEYSTORE_KEY_PASSWORD'],
          }
    )
    track = 'release'
    if ENV['VERSION_TAG'].include? 'alpha'
      track = 'internal'
    elsif ENV['VERSION_TAG'].include? 'beta'
      track = 'beta'
    else
      track = 'release'
    end
    upload_to_play_store(track: track)
  end
end
