opt_out_usage
default_platform(:android)

platform :android do
  desc "Lane for distributing app with Github releases"
  lane :github do
    gradle(
      task: "assemble",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "/home/runner/work/Youamp/Youamp/keystore.jks",
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEYSTORE_KEY_PASSWORD'],
      }
    )
    set_github_release(
      repository_name: "siper/Youamp",
      api_token: ENV['TOKEN_GITHUB'],
      name: ENV['VERSION_TAG'],
      tag_name: ENV['VERSION_TAG'],
      is_generate_release_notes: true,
      upload_assets: ["app/build/outputs/apk/release/app-release.apk"]
    )
  end

  desc "Lane for distributing app with Play Store"
  lane :play_store do
    gradle(
      task: "bundle",
      build_type: "Release",
      properties: {
        "android.injected.signing.store.file" => "/home/runner/work/Youamp/Youamp/keystore.jks",
        "android.injected.signing.store.password" => ENV['KEYSTORE_PASSWORD'],
        "android.injected.signing.key.alias" => ENV['KEYSTORE_KEY_ALIAS'],
        "android.injected.signing.key.password" => ENV['KEYSTORE_KEY_PASSWORD'],
      }
    )
    track = 'release'
    if ENV['VERSION_TAG'].include? 'alpha'
      track = 'alpha'
    elsif ENV['VERSION_TAG'].include? 'beta'
      track = 'beta'
    else
      track = 'release'
    end
    upload_to_play_store(
      track: track,
      sync_image_upload: true,
      skip_upload_apk: true
    )
  end

  desc "Lane for validate app metadata in Play Store"
    lane :play_store_validate do
      upload_to_play_store(
        track: 'alpha',
        sync_image_upload: true,
        validate_only: true,
        skip_upload_aab: true,
        skip_upload_apk: true
      )
    end
end
