name: Check and Build

on:
  pull_request:
    branches: [ master ]

jobs:
  check_commits:
    name: Check commits
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: webiny/action-conventional-commits@v1.3.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    name: Run Ktlint checks
    runs-on: ubuntu-latest
    needs: check_commits
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          fail_on_error: true


  lint:
    name: Run lint checks
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: check_commits
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Lint
        run: ./gradlew lint

  build_android:
    name: Build android
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [ check_commits, lint, ktlint ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew androidApp:assemble

  build_desktop:
    name: Build desktop
    runs-on: ubuntu-latest
    needs: [ check_commits, lint, ktlint ]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew desktopApp:packageReleaseDistributionForCurrentOS
