name: Build and Upload release

on:
  push:
    tags:
      - 'v*'

jobs:
  CI:
    name: Build and Upload release
    runs-on: ubuntu-latest

    env:
      GOOGLE_SERVICE_KEY_JSON: ${{ secrets.GOOGLE_SERVICE_KEY_JSON }}
      KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
      TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
      VERSION_TAG: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.3'
          bundler-cache: true

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate google-service-key.json file
        run: echo ${{secrets.GOOGLE_SERVICE_KEY_JSON}} | base64 -d > /home/runner/work/Youamp/Youamp/google-service-key.json

      - name: Generate .jks file
        run: echo ${{secrets.KEYSTORE_JKS}} | base64 -d > /home/runner/work/Youamp/Youamp/keystore.jks

      - name: Publish github release with fastlane
        run: bundle exec fastlane github

      - name: Publish Play Store release with fastlane
        run: bundle exec fastlane play_store