name: Build and Release KMP Application

on:
  push:
    tags:
      - 'v*'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build:
    name: Build for all targets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ android, linux, macos, windows ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        if: matrix.target == 'android'
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        if: matrix.target == 'android'
        run: |
          echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > /home/runner/work/Youamp/Youamp/androidApp/keystore.jks
        env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}

      - name: Build Android
        if: matrix.target == 'android'
        run: |
          ./gradlew :androidApp:assembleRelease \
            -Pandroid.injected.signing.store.file=/home/runner/work/Youamp/Youamp/androidApp/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Build Desktop
        if: matrix.target != 'android'
        run: |
          ./gradlew :desktopApp:createDistributable \
            -Ptarget=${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}-build
          path: |
            androidApp/build/outputs/apk/release/*.apk
            desktopApp/build/compose/binaries/main/app/${{ matrix.target }}/*

  create-release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: |
            Multiplatform release for Android, Windows, macOS and Linux.
            See artifacts for each platform.
          files: |
            artifacts/android-build/*.apk
            artifacts/linux-build/*
            artifacts/macos-build/*
            artifacts/windows-build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}