name: Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build-desktop:
    name: Build desktop
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Desktop
        run: |
          ./gradlew :desktopApp:packageDistributionForCurrentOS

      - name: Upload artifacts deb
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest'
        with:
          name: linux-build
          path: |
            desktopApp/build/compose/binaries/main/deb/*.deb

      - name: Upload artifacts msi
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: windows-build
          path: |
            desktopApp/build/compose/binaries/main/msi/*.msi

      - name: Upload artifacts dmg
        uses: actions/upload-artifact@v4
        if: matrix.os == 'macOS-latest'
        with:
          name: macos-build
          path: |
            desktopApp/build/compose/binaries/main/dmg/*.dmg

  build-android:
    name: Build android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_JKS }}" | base64 --decode > /home/runner/work/Youamp/Youamp/androidApp/keystore.jks
        env:
          KEYSTORE_JKS: ${{ secrets.KEYSTORE_JKS }}

      - name: Build Android
        run: |
          ./gradlew :androidApp:assembleRelease \
            -Pandroid.injected.signing.store.file=/home/runner/work/Youamp/Youamp/androidApp/keystore.jks \
            -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
            -Pandroid.injected.signing.key.alias=${{ secrets.KEYSTORE_KEY_ALIAS }} \
            -Pandroid.injected.signing.key.password=${{ secrets.KEYSTORE_KEY_PASSWORD }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-build
          path: |
            androidApp/build/outputs/apk/release/*.apk

  create-release:
    name: Create Release
    needs: [ build-desktop, build-android ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          body: |
            Multiplatform release for Android, Windows, macOS and Linux.
            See artifacts for each platform.
          files: |
            artifacts/**/*.apk
            artifacts/**/*.deb
            artifacts/**/*.dmg
            artifacts/**/*.msi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}